#!/bin/bash  
if test "$1" = ""; then
	echo
	java -cp @deploy-dir/mp3agic.jar com.mpatric.mp3agic.app.Mp3Details
	echo
	echo "Displays the details of the specified mp3 file(s)" 
	echo
	echo "Usage: mp3details [filename specifier]"
	echo "Example: mp3details myaudio/*.mp3"
	echo
	exit 2
fi      
fin=0
while ! ((fin)); do
	if test "$1" = ""; then
		fin=1
	else
		if [ -f "${1}" ]; then
			java -cp @deploy-dir/mp3agic.jar com.mpatric.mp3agic.app.Mp3Details "${1}"
		fi
		shift
	fi
done
