#!/bin/bash  
if test "$1" = ""; then
	echo
	java -cp @deploy-dir/mp3agic.jar com.mpatric.mp3agic.app.Mp3Rename
	echo
	echo "Renames the specified mp3 file(s) using data from the mp3 id3 tags"
	echo
	echo "Usage: mp3rename [rename pattern][filename spec]"
	echo
	echo "  The rename pattern may contain the following tokens:"
	echo "    @N - Track number"
	echo "    @A - Artist"
	echo "    @T - Title"
	echo "    @L - Album"
	echo "    @Y - Year"
	echo "    @G - Genre"
	echo
	echo "Example: mp3rename \"@N - @A - @T\" myaudio/*.mp3"
	echo
 	exit 2
fi      
OPTIONS+=("${1}")
shift
fin=0
while ! ((fin)); do
	if test "$1" = ""; then
		fin=1
	else
		if [ -f "${1}" ]; then
            java -cp @deploy-dir/mp3agic.jar com.mpatric.mp3agic.app.Mp3Rename "${OPTIONS[@]}" "${1}"
		fi
		shift
	fi
done
